### ISSUE TITLE
https://github.com/GoDjango/godjango-site.git

### ISSUE THREAD

**Issue by AnthonyWJones** [GoDjango/astral_test_mission#1]
What happened to this repo? I was learning a lot from your video: https://www.youtube.com/watch?v=c_17jALtLbQ .

**Comment by GoDjango** [comment]
It's not me =) I've never made any videos. This repo is only test task for new job.

**Comment by AnthonyWJones** [comment]
Oh, okay, I see what happened now. I guess the guy was just using a repo you had up at one time. Sorry. Thanks for the quick reply, though.
